#https://www.mkdocs.org/user-guide/configuration/#
site_name: MMRF Virtual Lab Documentation
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/theMMRF/docs-gen3.git
nav:
  - Home: index.md
  - About MMRF Virtual Lab: mmrf-resources/about.md
  - MMRF Community: mmrf-resources/community.md
  - User Guide:
    - mmrf-resources/user-guide/index.md # user guide home page, describing the contents of the user guide and linking to sections
    - Cohort Builder: mmrf-resources/user-guide/cohort-builder.md
    - Repository & Data Download: mmrf-resources/user-guide/repository.md
    - Mutation Frequency: mmrf-resources/user-guide/mutation-frequency.md
    - Clinical Data Analysis: mmrf-resources/user-guide/clinical-data-analysis.md
    - Cohort Comparison: mmrf-resources/user-guide/cohort-comparison.md
  - MMRF CoMMpass:
    - mmrf-resources/mmrf-commpass/index.md
    - Data Processing & Harmonization: mmrf-resources/mmrf-commpass/data-processing.md
    - Interim Analysis Data Access: mmrf-resources/mmrf-commpass/historic-ia.md
  #- Blog:
  #  - blog/index.md
  #- Frequently Asked Questions: gen3-resources/faq.md
  #- gen3-resources/glossary.md
  - Coming Soon: mmrf-resources/coming-soon.md

theme:
  logo: img/VirtualLab-FINAL_R_RGB_Platinum.png
  favicon: img/MMRF20Square_Plum_CMYK.png
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path
  custom_dir: overrides

  palette:
    - primary: black


   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: brh_platform
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: brh_platform_dark
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/dd.js
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      auto_title: true
plugins:
  - search
  - tags
  - blog:
      enabled: true
      authors: true
      authors_file: blog/authors.yml
      blog_dir: blog
      blog_toc: true
  - mkdocs-video:
      is_video: True

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/multiple-myeloma-research-foundation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCQVbiTmG0D6KIt1l49vV6bA
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/theMMRF/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/accounts/login/?next=%2Fthemmrf%2F&source=omni_redirect
    - icon: fontawesome/brands/twitter
      link: https://x.com/theMMRF?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
